blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/ssfdre38/match-mania/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/ssfdre38/match-mania/wiki
    about: Check out the wiki for guides and documentation
